[package]
name = "jay-bytecode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"

[build-dependencies]
toml = "0.8.6"
serde = "1.0"
serde_derive = "1.0"
